version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SHOPIFY_API_KEY=$SHOPIFY_API_KEY
    ports:
      - "8081:8081"
    environment:
        - SHOPIFY_API_KEY=$SHOPIFY_API_KEY
        - SHOPIFY_API_SECRET=$SHOPIFY_API_SECRET
        - HOST=$HOST
        - SCOPES=$SCOPES
        - PORT=$PORT
